言語処理100本ノック回答提出
pepabo-college/3rd-pullrequest-tutorial pull request #6
Opened 2017-06-02 05:21 UTC by bake0937

answer-00.rbを提出します

2017-06-02 05:29 UTC, litencatt commented on chocolate/answer-00.rb
> +"stressed".reverse
こんな感じでOKです:+1:

2017-06-02 07:59 UTC, dp42 commented on chocolate/answer-09.rb
> +}
余った時間に自分も書いてみました。
別解としてご参照ください

```ruby
sentence = "I couldn't believe that I could actually understand what I was reading : the phenomenal power of the human mind ."
words = sentence.split(' ')

words.map! do |word|
  if word.length > 4
    first_char = word[0]
    last_char = word[word.length - 1]
    shuffled_chars = word[1..(word.length - 2)].split('').shuffle.join
    word = first_char + shuffled_chars + last_char
  else
    word
  end
end

puts words.join(' ')
```

2017-06-02 08:13 UTC, udzura commented on chocolate/answer-09.rb
> +}
yoine!!

2017-06-02 09:31 UTC, udzura requested changes

2017-06-02 09:31 UTC, udzura commented on chocolate/answer-09.rb
> +    word.sub!(/#{first_char}/,'')
ふふふ、この実装は問題があるかも...

2017-06-02 09:31 UTC, udzura commented on chocolate/answer-09.rb
> +    word.sub!(/#{first_char}/,'')
あ、結果的にOKになりますね。でもちょっと不適切な箇所があります。考えてみるといいかも

2017-06-02 09:41 UTC, udzura commented on chocolate/answer-01.rb
> +answer = str.split('').values_at(0, 2, 4, 6).join
この問題ですが、もし

* 奇数番目の文字だけを抜き出す
* 任意の文字を受け取るようにする

と一般化したらどう書くといいか？を考えてみていただけますかっ

2017-06-05 00:33 UTC, sunecosuri commented on chocolate/answer-09.rb
> +    word.sub!(/#{first_char}/,'')
if word.length>4
       #単語を一文字ずつ配列化
        chars = word.chars
        #最初の要素と最後の要素を削除して取得
        first = chars.shift
        last  = chars.pop
        #最初の文字＋シャッフルした文字列＋最後の文字をjoin
        ([first] + chars.shuffle + [last]).join
else
        word
end

僕も書いてみました…

2017-06-05 05:12 UTC, udzura commented on chocolate/answer-09.rb
> +    word.sub!(/#{first_char}/,'')
インデントがやばいね...
Array#shift/pop 使うのスマート 👍

2017-06-05 05:14 UTC, udzura commented on chocolate/answer-09.rb
> +    shuffle_char = word[0] + word_shuffle + word[-1]
LGTM

2017-06-05 05:16 UTC, udzura commented on chocolate/answer-01.rb
> +p answer
LGTM

2017-06-05 05:17 UTC, merged

2017-06-07 15:10 UTC, june29 commented
インデントサイズがファイルによって違ったりしている？ `answer-03.rb` `answer-08.rb` がやんちゃな感じで、どういう入力環境で作業しているのだろう？とちょっと気になりました :eyes: